### ISSUE TITLE
Steps fail with null pointer exception!

### ISSUE THREAD

**Issue by osmanburucu-ibm** [ibm-datapower/datapower-configuration-manager#109]
on some steps (like create domain, or save configuration) i get an null pointer exception. have uploaded my application (based on the tutorial for this plugin) and the error messages

-- step is create domain and here the output:
================================================================================
plugin: DataPower, id: com.ibm.datapower, version: 23
plugin command: '/opt/ucd/agent/opt/groovy-2.4.15/bin/groovy' '-cp' '/opt/ucd/agent/var/plugins/com.ibm.datapower_23_1b4d6ef5935184fdf0b2d4ef2aaf1af7a031bd86022cd00599fce22f8a17b7be/classes' '/opt/ucd/agent/var/plugins/com.ibm.datapower_23_1b4d6ef5935184fdf0b2d4ef2aaf1af7a031bd86022cd00599fce22f8a17b7be/RunDeployDotAnt.groovy' '/opt/ucd/agent/var/temp/logs-260bb400-3058-4a4d-a80f-e7594d345187/input.props' '/opt/ucd/agent/var/temp/logs-260bb400-3058-4a4d-a80f-e7594d345187/output.props' '-Ddomain=@newDomainName@' '-Denvironment=@environment@' 'domain-create'
working directory: /opt/ucd/agent/var/work/ozdp1
properties:
  PLUGIN_INPUT_PROPS=/opt/ucd/agent/var/temp/logs-260bb400-3058-4a4d-a80f-e7594d345187/input.props
  PLUGIN_OUTPUT_PROPS=/opt/ucd/agent/var/temp/logs-260bb400-3058-4a4d-a80f-e7594d345187/output.props
  addlProperties=test=test
  environment=h
  hostname=caplonsgprd-3.integration.ibmcloud.com
  memorySize=default
  newDomainName=ozzymandias
  portXMI=15908
  pwd=****
  uid=ucd 
environment:
  AGENT_HOME=/opt/ucd/agent
  AH_AUTH_TOKEN=****
  AH_WEB_URL=https://cos8a.local.net:8443
  AUTH_TOKEN=****
  DS_AUTH_TOKEN=****
  DS_SYSTEM_ENCODING=UTF-8
  JAVA_OPTS=-Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
  PLUGIN_HOME=/opt/ucd/agent/var/plugins/com.ibm.datapower_23_1b4d6ef5935184fdf0b2d4ef2aaf1af7a031bd86022cd00599fce22f8a17b7be
  UD_DIALOGUE_ID=260bb400-3058-4a4d-a80f-e7594d345187
  WE_ACTIVITY_ID=17592694-e748-1a6a-353f-15f26c125951
================================================================================
java.lang.NullPointerException: Cannot invoke method trim() on null object

-- STEP error log:

Full Error Details
Error Description
Plugin step activity failed. Check the output log and output properties for additional information. If using a custom post-processing script, keep in mind that plugin steps will always be marked as failed unless the output property "Status" is set to "Success".
Error Stack Trace
java.lang.Exception: Plugin step activity failed. Check the output log and output properties for additional information. If using a custom post-processing script, keep in mind that plugin steps will always be marked as failed unless the output property "Status" is set to "Success".
    at com.urbancode.ds.subsys.deploy.workflow.activity.PluginCommandActivity.activityFailed(PluginCommandActivity.java:1252)
    at com.urbancode.ds.subsys.deploy.workflow.activity.PluginCommandActivity.activityFailed(PluginCommandActivity.java:1239)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.urbancode.air.workflow.ExecutionContext.executeActivityMethod(ExecutionContext.java:626)
    at com.urbancode.air.workflow.ExecutionContext.executeActivityMethodByName(ExecutionContext.java:518)
    at com.urbancode.air.workflow.DispatchedTask.execute(DispatchedTask.java:230)
    at com.urbancode.air.workflow.WorkflowRuntime$6.run(WorkflowRuntime.java:309)
    at com.urbancode.air.workflow.WorkflowRuntime$WorkflowTaskAction.call(WorkflowRuntime.java:410)
    at com.urbancode.air.workflow.WorkflowRuntime$WorkflowTaskAction.call(WorkflowRuntime.java:379)
    at com.urbancode.air.workflow.WorkflowRuntime$TxWrapper.call(WorkflowRuntime.java:574)
    at com.urbancode.air.workflow.ExceptionLogWrapper.call(ExceptionLogWrapper.java:43)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.urbancode.air.workflow.Scheduler$Runner.run(Scheduler.java:77)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
    at com.urbancode.commons.util.concurrent.NamedThreadFactory$NamedThread.run(NamedThreadFactory.java:44)

**Comment by osmanburucu-ibm** [comment]
I am using UCD 7.1.1 and latest DataPower Plugin (v23). server/agent runs on CentOS 8, openjdk 8

**Comment by osmanburucu-ibm** [comment]
it should be fixed now with issue #111
