### ISSUE TITLE
BackupDevice step is failing

### ISSUE THREAD

**Issue by tomashudec** [ibm-datapower/datapower-configuration-manager#11]
BackupDomain is working correctly, but when I execute BackupDevice operation, it everytime fails with following error (stack-trace):

BUILD FAILED
/opt/ibm-ucd/ucdagent/var/plugins/com.ibm.datapower_8_c153924d27a2723f17dc9a0971a7b6f8b09bf7f15502419ea57ca0370535a7d8/dcm/deploy.ant.xml:191: The following error occurred while executing this line:
/opt/ibm-ucd/ucdagent/var/plugins/com.ibm.datapower_8_c153924d27a2723f17dc9a0971a7b6f8b09bf7f15502419ea57ca0370535a7d8/dcm/src/dcm-taskdefs.ant.xml:62: java.lang.RuntimeException: Failed to backup on nlutdcsdp100-mgt0.nl.eu.abnamro.com
at com.ibm.dcm.Soma.doBackup(Soma.java:536)
at com.ibm.dcm.Soma.doBackupDevice(Soma.java:602)
at com.ibm.dcm.Soma.performOperation(Soma.java:98)
at com.ibm.dcm.taskWdp.execute(taskWdp.java:203)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
at java.lang.reflect.Method.invoke(Method.java:620)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
at java.lang.reflect.Method.invoke(Method.java:620)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
at java.lang.reflect.Method.invoke(Method.java:620)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
at java.lang.reflect.Method.invoke(Method.java:620)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.Target.execute(Target.java:435)
at org.apache.tools.ant.Target.performTasks(Target.java:456)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
at org.apache.tools.ant.Main.runBuild(Main.java:853)
at org.apache.tools.ant.Main.startAnt(Main.java:235)
at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
 
Total time: 51 seconds
com.urbancode.air.ExitCodeException: Command failed with exit code: 1

**Comment by richgroot** [comment]
What version of DP firmware is on that appliance?

**Comment by smartgoods** [comment]
Hello Rich

We are using the latest firmware, 7.0.3

With Regards,
Deborah Brown

On Tue, Mar 8, 2016 at 1:05 PM, Rich Groot <notifications@github.com> wrote:

> What version of DP firmware is on that appliance?
>
> On Mon, Mar 7, 2016 at 10:20 PM, tomashudec <notifications@github.com>
> wrote:
>
>
> > BackupDomain is working correctly, but when I execute BackupDevice
> > operation, it everytime fails with following error (stack-trace):
> >
> > BUILD FAILED
> >
> /opt/ibm-ucd/ucdagent/var/plugins/com.ibm.datapower_8_c153924d27a2723f17dc9a0971a7b6f8b09bf7f15502419ea57ca0370535a7d8/dcm/deploy.ant.xml:191:
> > The following error occurred while executing this line:
> >
> /opt/ibm-ucd/ucdagent/var/plugins/com.ibm.datapower_8_c153924d27a2723f17dc9a0971a7b6f8b09bf7f15502419ea57ca0370535a7d8/dcm/src/dcm-taskdefs.ant.xml:62:
> > java.lang.RuntimeException: Failed to backup on
> > nlutdcsdp100-mgt0.nl.eu.abnamro.com
> > at com.ibm.dcm.Soma.doBackup(Soma.java:536)
> > at com.ibm.dcm.Soma.doBackupDevice(Soma.java:602)
> > at com.ibm.dcm.Soma.performOperation(Soma.java:98)
> > at com.ibm.dcm.taskWdp.execute(taskWdp.java:203)
> > at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > at
> >
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
> > at
> >
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
> > at java.lang.reflect.Method.invoke(Method.java:620)
> > at
> >
> org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
> > at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
> > at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
> > at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
> > at
> >
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
> > at java.lang.reflect.Method.invoke(Method.java:620)
> > at
> >
> org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
> > at org.apache.tools.ant.Task.perform(Task.java:348)
> > at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
> > at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
> > at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
> > at
> >
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
> > at java.lang.reflect.Method.invoke(Method.java:620)
> > at
> >
> org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
> > at org.apache.tools.ant.Task.perform(Task.java:348)
> > at
> >
> org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
> > at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
> > at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
> > at
> >
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
> > at java.lang.reflect.Method.invoke(Method.java:620)
> > at
> >
> org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
> > at org.apache.tools.ant.Task.perform(Task.java:348)
> > at org.apache.tools.ant.Target.execute(Target.java:435)
> > at org.apache.tools.ant.Target.performTasks(Target.java:456)
> > at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
> > at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
> > at
> >
> org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
> > at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
> > at org.apache.tools.ant.Main.runBuild(Main.java:853)
> > at org.apache.tools.ant.Main.startAnt(Main.java:235)
> > at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
> > at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
> >
> > Total time: 51 seconds
> > com.urbancode.air.ExitCodeException: Command failed with exit code: 1
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ibm-datapower/datapower-configuration-manager/issues/11
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ibm-datapower/datapower-configuration-manager/issues/11#issuecomment-193755641>
> .
>



-- 
Met vriendelijke groet/ With kind regards,

Deborah Brown

**Comment by tomashudec** [comment]
I have some actual information about this issue: problem was on concrete DP appliance (working correctly on another one). However if DP does not return correct answer (exported data in xml format) it should not end with "stack-trace" error, but it should return more user-friendly result/error code.

**Comment by richgroot** [comment]
Yeah, the default Java and Ant error handling is somewhat unpleasant.  I wrote the DCM code to return useful error messages on the first line of the stack trace but controlling the stack trace itself, or at least limiting it to a few lines, isn't something that I'm familiar with.  Perhaps someone else who has the knowledge will contribute to the project.
