### ISSUE TITLE
UCD Plugin problem

### ISSUE THREAD

**Issue by samdjones** [ibm-datapower/datapower-configuration-manager#14]
Hello,

Please see below error output when attempting to execute the checkpoint task of the UCD plugin (latest version 8 - .zip downloaded directly from the UCD website). UBC is version 6.2.1.0.769568 running on Windows 7.

The key problem is at the bottom of the trace below: ..**dcm/dist/dcm.8.774073.jar is not found**

Upon inspecting the contents of the directory, there is a jar instead named "datapower-8.774073.jar"

I'm pretty sure this explains the problem. Note that the latest version of the DCM build from direct Github download builds it with the filename **dcm.8.774073.jar**, so I suspect there is simply problem with the way the plugin is packaged by the Ant build script.

Cheers,
Sam

================================================================================
plugin: DataPower, id: com.ibm.datapower, version: 8
plugin command: 'cmd' '/C' '"C:\Users\C16536\Apps\ucd-agent\opt\groovy-1.8.8\bin\groovy -cp C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577\classes C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577\RunDeployDotAnt.groovy C:\Users\C16536\Apps\ucd-agent\var\temp\logs7222969517215546302\input.props C:\Users\C16536\Apps\ucd-agent\var\temp\logs7222969517215546302\output.props "-Ddomain=@domainName@" "-Denvironment=@environment@" "-Dcheckpoint.name=@checkpoint@" checkpoint-save"'
working directory: C:\Users\C16536\Apps\ucd-agent\var\work\test-component
properties:
  PLUGIN_INPUT_PROPS=C:\Users\C16536\Apps\ucd-agent\var\temp\logs7222969517215546302\input.props
  PLUGIN_OUTPUT_PROPS=C:\Users\C16536\Apps\ucd-agent\var\temp\logs7222969517215546302\output.props
  addlProperties=
  checkpoint=Test
  domainName=test
  environment=DEV
  hostname=redacted
  portXMI=9090
  pwd=redacted
  uid=redacted
environment:
  AGENT_HOME=C:\Users\C16536\Apps\ucd-agent
  AH_AUTH_TOKEN=****
  AH_WEB_URL=http://localhost:9095
  AUTH_TOKEN=****
  DS_AUTH_TOKEN=****
  DS_SYSTEM_ENCODING=Cp1252
  JAVA_OPTS=-Dfile.encoding=Cp1252 -Dconsole.encoding=Cp1252
  PLUGIN_HOME=C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577
  UD_DIALOGUE_ID=70652883-db70-4628-ae54-a813c4176257
  WE_ACTIVITY_ID=023e1e65-8cdb-444f-8fe6-50b18032e171
================================================================================
 
C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577/dcm/apache-ant-1.9.6/bin/ant.bat -f C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577/dcm/deploy.ant.xml -Ddcm.dir=C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577/dcm -Dhost=192.168.220.130 -Dport=9090 -Duid=ucd-dcm-test -Dpwd=**** -Dwork.dir=C:\Users\C16536\Apps\ucd-agent\var\work\test-component\./tmp -Ddomain=unit-test-decorator-prototype-tls -Denvironment=DEV -Dcheckpoint.name=Test checkpoint-save
command: C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577\dcm\apache-ant-1.9.6\bin\ant.bat -f C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577/dcm/deploy.ant.xml -Ddcm.dir=C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577/dcm -Dhost=192.168.220.130 -Dport=9090 -Duid=ucd-dcm-test -Dpwd=**** -Dwork.dir=C:\Users\C16536\Apps\ucd-agent\var\work\test-component\./tmp -Ddomain=unit-test-decorator-prototype-tls -Denvironment=DEV -Dcheckpoint.name=Test checkpoint-save
Unable to locate tools.jar. Expected to find it in C:\Program Files\Java\jre1.8.0_45\lib\tools.jar
Buildfile: C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577\dcm\deploy.ant.xml
 
BUILD FAILED
C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577\dcm\deploy.ant.xml:134: The Ant property 'dcm.dir' doesn't seem to point to DCM since C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_f71931eed02d8c4fb2f2bcd5d9ecd54d0c94e6603f8324906e0ff5c1cf9f7577/dcm/dist/dcm.8.774073.jar is not found.
 
Total time: 0 seconds
com.urbancode.air.ExitCodeException: Command failed with exit code: 1

**Comment by samdjones** [comment]
I went ahead and attempted to fix the plugin by renaming the .jar file, zipping up and reinstalling into UBC. It seems to have fixed the issue but now I have a new one - see below.

Cheers,
Sam

C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_ef966181ab838a101029721132c28aae7e30b370355f2bd777c6887d6628fac3/dcm/apache-ant-1.9.6/bin/ant.bat -f C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_ef966181ab838a101029721132c28aae7e30b370355f2bd777c6887d6628fac3/dcm/deploy.ant.xml -Ddcm.dir=C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_ef966181ab838a101029721132c28aae7e30b370355f2bd777c6887d6628fac3/dcm -Dhost=192.168.220.130 -Dport=9090 -Duid=ucd-dcm-test -Dpwd=**** -Dwork.dir=C:\Users\C16536\Apps\ucd-agent\var\work\test-component\./tmp -Ddomain=unit-test-decorator-prototype-tls -Denvironment=DEV -Dcheckpoint.name=Test checkpoint-save
command: C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_ef966181ab838a101029721132c28aae7e30b370355f2bd777c6887d6628fac3\dcm\apache-ant-1.9.6\bin\ant.bat -f C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_ef966181ab838a101029721132c28aae7e30b370355f2bd777c6887d6628fac3/dcm/deploy.ant.xml -Ddcm.dir=C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_ef966181ab838a101029721132c28aae7e30b370355f2bd777c6887d6628fac3/dcm -Dhost=192.168.220.130 -Dport=9090 -Duid=ucd-dcm-test -Dpwd=**** -Dwork.dir=C:\Users\C16536\Apps\ucd-agent\var\work\test-component\./tmp -Ddomain=unit-test-decorator-prototype-tls -Denvironment=DEV -Dcheckpoint.name=Test checkpoint-save
Unable to locate tools.jar. Expected to find it in C:\Program Files\Java\jre1.8.0_45\lib\tools.jar
Buildfile: C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_ef966181ab838a101029721132c28aae7e30b370355f2bd777c6887d6628fac3\dcm\deploy.ant.xml
 
clean:
   [delete] Deleting directory C:\Users\C16536\Apps\ucd-agent\var\work\test-component\tmp
 
-init-dir:
    [mkdir] Created dir: C:\Users\C16536\Apps\ucd-agent\var\work\test-component\tmp
    [mkdir] Created dir: C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_ef966181ab838a101029721132c28aae7e30b370355f2bd777c6887d6628fac3\dcm\schemas
 
-check-std-args:
 
check-access:
 
BUILD FAILED
C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_ef966181ab838a101029721132c28aae7e30b370355f2bd777c6887d6628fac3\dcm\deploy.ant.xml:266: The following error occurred while executing this line:
C:\Users\C16536\Apps\ucd-agent\var\plugins\com.ibm.datapower_8_ef966181ab838a101029721132c28aae7e30b370355f2bd777c6887d6628fac3\dcm\src\dcm-taskdefs.ant.xml:192: java.io.FileNotFoundException: \schemas\xhtml1-transitional.dtd (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at com.ibm.dcm.SomaUtils.getDOM(SomaUtils.java:109)
	at com.ibm.dcm.Soma.doGetStatuses(Soma.java:2948)
	at com.ibm.dcm.Soma.performOperation(Soma.java:188)
	at com.ibm.dcm.taskWdp.execute(taskWdp.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at com.ibm.dcm.taskIf.execute(taskIf.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
 
Total time: 0 seconds
com.urbancode.air.ExitCodeException: Command failed with exit code: 1

**Comment by richgroot** [comment]
Sam,

Check that you are going to port 5550 (XML Management interface) rather
than 9090 (browser interface).  I think that the clue here is the complaint
that it can't find "\schemas\xhtml1-transitional.dtd", which indicates that
the response it is trying to parse is HTML rather than XML.

Thanks,
Rich

**Comment by samdjones** [comment]
Thanks for the tip re: incorrect port. It now works with my fixed(*) version of plugin after I corrected the port number. I've also had another team recreate the issue with the plugin downloaded from the UCD website. Do you agree it is a defect and approve of my fix?

Cheers,
Sam

* i.e. renamed datapower-*.jar to dcm-*.jar as-per my first comment

**Comment by samdjones** [comment]
\*Bump\*

Please confirm if my issue is real and my fix is legit or not. See Pull Request #21 - it appears to have address the same issue.

Cheers,
Sam

**Comment by richgroot** [comment]
Pull #21 done, which should clear up this problem.
