### ISSUE TITLE
upload-dir giving error

### ISSUE THREAD

**Issue by gitUser2k17** [ibm-datapower/datapower-configuration-manager#38]
Hi,

I have tried upload-dir command today, it is giving me errors. All required properties are set but it is still throwing the following error may be because 'https://x.x.x.x:5550 /service/mgmt/current' there is a space between port and uri. Not sure where to correct this ( is it in Java ?? )

1) I have tried other commands like uploading a single file, importing services, they are all fine.
2) I have taken the same SOMA request from the -Dcapturesoma generated log and tried that with a testing tool to DP by removing space, it worked fine. Only the ant command line is giving a problem.

Can someone please help ?

upload-dir:

BUILD FAILED
C:\Users\S\Documents\svn_workspace\Automation\Datapower Configuration Manager\deploy.ant.xml:1221: java.net.MalformedURLException: For input string: "5550 "
        at java.net.URL.<init>(URL.java:627)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at com.ibm.dcm.SSLConnection.sendAndReceive(SSLConnection.java:153)
        at com.ibm.dcm.taskDpupload.createDirectory(taskDpupload.java:393)
        at com.ibm.dcm.taskDpupload.upload(taskDpupload.java:270)
        at com.ibm.dcm.taskDpupload.execute(taskDpupload.java:119)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
Caused by: java.lang.NumberFormatException: For input string: "5550 "
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:216)
        at java.net.URL.<init>(URL.java:622)
        ... 22 more

Total time: 3 seconds

Thanks.

**Comment by gitUser2k17** [comment]
Hi,

I have researched and this seems to be problem with the property entries I have defined. Port has space in it, others are truncating the space but upload-dir is using the port as is.  I removed space in properties and this is working fine now.

Thank you.
