### ISSUE TITLE
Create Objects Error

### ISSUE THREAD

**Issue by bmarur** [ibm-datapower/datapower-configuration-manager#62]
Hello Experts,

I ran in to an issue while executing Create Object from definitions DCM operation, It looks like the JAVA codeis unable to parse the file internally. I have ran the command with a '-v' flag for a more descriptive error however this operation seems to error out in JAVA code.

**Command**:` ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-b0r.company.com -Dport=5550 -Duid=xgidbrt -Ddomain=Test_Build_DEMO -Denvironment=DEV -Dobjects.file="C:/Users/user/Documents/dcm/ant_tutorials/definitions/deployment_policy_definitions.xml" objects-from-def`

**PFB Error logs**

`Apache Ant(TM) version 1.9.2 compiled on July 8 2013
Buildfile: C:\Users\user\Documents\dcm\dcm\deploy.ant.xml
Detected Java version: 1.8 in: C:\Program Files\Java\jdk1.8.0_131\jre
Detected OS: Windows 7
parsing buildfile C:\Users\user\Documents\dcm\dcm\deploy.ant.xml with URI = file:/C:/Users/user/Documents/dcm/dcm/deploy.ant.xml
Project base dir set to: C:\Users\user\Documents\dcm\dcm
parsing buildfile jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/apache-ant-1.9.2/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/apache-ant-1.9.2/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
[available] Searching C:\Users\user\Documents\dcm\dcm
[available] Found: dist\dcm.jar in C:\Users\user\Documents\dcm\dcm
parsing buildfile jar:file:/C:/Users/user/Documents/dcm/dcm/dist/dcm.jar!/com/ibm/antlib.xml with URI = jar:file:/C:/Users/user/Documents/dcm/dcm/dist/dcm.jar!/com/ibm/antlib.xml from a zip file
[antlib:ibm] Could not load definitions from resource ibm/antlib.xml. It could not be found.
Importing file C:\Users\user\Documents\dcm\dcm\src\dcm-taskdefs.ant.xml from C:\Users\user\Documents\dcm\dcm\deploy.ant.xml
Overriding previous definition of reference to ant.projectHelper
parsing buildfile C:\Users\user\Documents\dcm\dcm\src\dcm-taskdefs.ant.xml with URI = file:/C:/Users/user/Documents/dcm/dcm/src/dcm-taskdefs.ant.xml
 [macrodef] creating macro  backupDevice
 [macrodef] creating macro  exportObject
 [macrodef] creating macro  exportObjects
 [macrodef] creating macro  backupDomains
 [macrodef] creating macro  checkDeviceAccess
 [macrodef] creating macro  ensureDPSchema
 [macrodef] creating macro  createDomain
 [macrodef] creating macro  deleteDomain
 [macrodef] creating macro  disableObject
 [macrodef] creating macro  disableObjects
 [macrodef] creating macro  downloadFiles
 [macrodef] creating macro  downloadFilestore
 [macrodef] creating macro  enableObject
 [macrodef] creating macro  enableObjects
 [macrodef] creating macro  exportConfig
 [macrodef] creating macro  firmwareRollback
 [macrodef] creating macro  firmwareUpdate
 [macrodef] creating macro  getDomainStatus
 [macrodef] creating macro  getServiceStatus
 [macrodef] creating macro  idcredFromPKCS12
 [macrodef] creating macro  idcredFromKeyAndCert
 [macrodef] creating macro  importConfig
 [macrodef] creating macro  importConfigDPO
 [macrodef] creating macro  listFilestore
 [macrodef] creating macro  objectCreateByCopying
 [macrodef] creating macro  objectCreateByInline
 [macrodef] creating macro  objectCreateFromExport
 [macrodef] creating macro  objectDelete
 [macrodef] creating macro  objectModify
 [macrodef] creating macro  quiesceDomain
 [macrodef] creating macro  quiesceService
 [macrodef] creating macro  rawMgmtCall
 [macrodef] creating macro  removeCheckpoint
 [macrodef] creating macro  resetDomainConventionally
 [macrodef] creating macro  resetDomainDeleteCreate
 [macrodef] creating macro  restartDomain
 [macrodef] creating macro  restoreBackup
 [macrodef] creating macro  rewriteExport
 [macrodef] creating macro  rollbackCheckpoint
 [macrodef] creating macro  saveCheckpoint
 [macrodef] creating macro  saveDomainIfChanged
 [macrodef] creating macro  saveDomainIfChangedPrompt
 [macrodef] creating macro  saveDomainUnconditionally
 [macrodef] creating macro  secureBackup
 [macrodef] creating macro  setLogLevel
 [macrodef] creating macro  valcredFromFiles
 [macrodef] creating macro  unimportConfig
 [macrodef] creating macro  unquiesceDomain
 [macrodef] creating macro  unquiesceService
 [macrodef] creating macro  xalan
 [macrodef] creating macro  defprop
 [macrodef] creating macro  defprop-set
Overriding previous definition of reference to ant.projectHelper
Build sequence for target(s) `objects-from-def' is [clean, -init-dir, -check-std-args, check-access, objects-from-def]
Complete build sequence is [clean, -init-dir, -check-std-args, check-access, objects-from-def, backup-device, import-from-def, import-changed, domain-delete, domain-create, save, domain-recreate, service-unquiesce, ltpa-password, idcred-from-key-and-cert, firmware-rollback, main, reboot, restore-backup, service-quiesce, download-files, host-alias-set, service-status, secure-backup-device, load-balancer-group-from-def, checkpoint-save, host-alias-remove, backup-domains, checkpoint-delete, set-log-level, domain-init, checkpoint-restore, create-tam-files, debug, valcred-from-dir, import-dpo, certificate-from-def, domain-unquiesce, idcred-from-def, upload-from-def, key-from-def, domain-quiesce, idcred-from-p12, domain-reset, object-status, raw-mgmt-call, upload-dir, export-object, valcred-from-def, domain-restart, firmware-update, , export-objects]

clean:
   [delete] Deleting directory C:\Users\user\Documents\dcm\dcm\tmp
   [delete] Deleting C:\Users\user\Documents\dcm\dcm\tmp\object-create.xml
   [delete] Deleting C:\Users\user\Documents\dcm\dcm\tmp\objects.ant.xml
   [delete] Deleting directory C:\Users\user\Documents\dcm\dcm\tmp

-init-dir:
    [mkdir] Created dir: C:\Users\user\Documents\dcm\dcm\tmp
    [mkdir] Skipping C:\Users\user\Documents\dcm\dcm\schemas because it already exists.

-check-std-args:
    [input] What is the password for 'xxxxx' on nc-wec-esbgw-b0r.company.com?
xxxxxx
Override ignored for property "port"

check-access:

objects-from-def:
[available] Found: C:\Users\user\Documents\dcm\ant_tutorials\definitions\deployment_policy_definitions.xml
    [nxslt] nxslt running ./src/remove-unwanted-elements.xsl on C:/Users/user/Documents/dcm/ant_tutorials/definitions/deployment_policy_definitions.xml producing tmp
    [nxslt] Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
    [nxslt] Warning: encoding "UTF-8" not supported, using UTF-8
    [nxslt] nxslt running ./src/objects-to-ant.xsl on tmp producing C:\Users\user\Documents\dcm\dcm\tmp/objects.ant.xml
    [nxslt] Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
    [nxslt] Warning: encoding "UTF-8" not supported, using UTF-8
Project base dir set to: C:\Users\user\Documents\dcm\dcm
      [ant] calling target(s) [default] in build file C:\Users\user\Documents\dcm\dcm\tmp\objects.ant.xml
parsing buildfile C:\Users\user\Documents\dcm\dcm\tmp\objects.ant.xml with URI = file:/C:/Users/user/Documents/dcm/dcm/tmp/objects.ant.xml
Project base dir set to: C:\Users\user\Documents\dcm\dcm
parsing buildfile jar:file:/C:/Users/user/Documents/dcm/dcm/dist/dcm.jar!/com/ibm/antlib.xml with URI = jar:file:/C:/Users/user/Documents/dcm/dcm/dist/dcm.jar!/com/ibm/antlib.xml from a zip file
Trying to override old definition of datatype antlib:ibm:nested
[available] Found: schemas\XI52.7.2.0.14.dpschema.xml
     [echo] Using C:\Users\user\Documents\dcm\dcm\schemas/XI52.7.2.0.14.dpschema.xml for nc-wec-esbgw-b0r.company.com
    [nxslt] nxslt running ./src/object-modify.xsl on C:\Users\user\Documents\dcm\dcm\tmp/object-create.xml producing new_config
    [nxslt] Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
    [nxslt] Warning: encoding "UTF-8" not supported, using UTF-8
    [nxslt] SystemId Unknown; Line #113; Column #38; Attempting to set-config for a type of object (set-config) that is not listed in the schema!
    [nxslt] (Location of error unknown)Stylesheet directed termination

BUILD FAILED
C:\Users\user\Documents\dcm\dcm\deploy.ant.xml:1140: The following error occurred while executing this line:
C:\Users\user\Documents\dcm\dcm\tmp\objects.ant.xml:18: The following error occurred while executing this line:
C:\Users\user\Documents\dcm\dcm\src\dcm-taskdefs.ant.xml:2039: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.StringBuffer.charAt(StringBuffer.java:202)
        at com.ibm.dcm.SomaUtils.xmlNoHeader(SomaUtils.java:180)
        at com.ibm.dcm.taskNxslt.execute(taskNxslt.java:161)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:179)
        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:93)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:391)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 8 seconds
`

I have attached the definitions file for your reference

[deployment_policy_definitions.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/1113379/deployment_policy_definitions.txt)

Please let me know If there is something wrong with my Command or Definitions File

Thanks,
Bharath

**Comment by nhmathis** [comment]
Hi Bharath,

The error is a result of the unknown `<set-config>` element. This is not valid syntax for the deployment policy file. Looking at the deployment policy, it looks as if you copied an object from the `export.xml`, which should be valid.

For those not familiar with the `object-*` elements, you will want to look at this [documentation](https://github.com/ibm-datapower/datapower-configuration-manager/wiki/dcm:object-*-elements).

-Nick
