### ISSUE TITLE
Review Changes - config-get-diff

### ISSUE THREAD

**Issue by sekhardutta** [ibm-datapower/datapower-configuration-manager#80]
Hi Team

I am trying to get config differences after deployment using DCM. I am able to achieve this using a specific Class for example class="B2BGateway" name="all-objects" but when I try Class="all-classes"  name="all-objects" it is throwing an error after 15min as below.  I have to get all differences not only related to specif class. Any hep would be appreciated.

D:\dcm\deploy.ant.xml:943: java.lang.RuntimeException: Failed to compute the requested diff.
        at com.ibm.dcm.Soma.doGetDiff(Soma.java:2744)
        at com.ibm.dcm.Soma.performOperation(Soma.java:182)
        at com.ibm.dcm.taskWdp.execute(taskWdp.java:203)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:853)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

Thanks
Sekhar Dutta

**Comment by nhmathis** [comment]
Could you please post the full successful and failure plugin logs? There is important information that's useful for debugging. Feel free to redact the any sensitive information (IP Address, username, etc) .

**Comment by richgroot** [comment]
Can you do the same comparison via the web browser?  This will help
identify whether the problem is in the code that parses the diff response,
or on the DP side.

**Comment by sekhardutta** [comment]
I have updated my params based on the java method doGetDiff as below and it is working fine
<from-class>all-classes</from-class>
<from-name>all-objects</from-name>
<from-persisted>true</from-persisted>			
<to-class>all-classes</to-class>
<to-name>all-objects</to-name>
<to-persisted>false</to-persisted>

But when we give as below it is failing with the error  java.lang.RuntimeException: Failed to compute the requested diff.
<class>all-classes</class>
<name>all-objects</name>
<from-persisted>true</from-persisted>
<to-persisted>false</to-persisted>
<recursive>true</recursive>

Now, the new problem I see is when I run get configuration changes, all action which were created dynamically are also added. Normally we exclude these using WEBGUI with option "Exclude generated and external data". Is there any equivalent option we have here ? Any idea?

**Comment by richgroot** [comment]
Interesting. The SOMA schema for the get-diff operation does not have any
way to specify the inclusion or exclusion of generated objects.  I strongly
suspect that the underlying UI code is doing a get-diff that explicitly
specifies each of the objects in its get-diff request, rather than using
the all-classes and all-objects flags.  It is certainly possible to do
something similar here, but that code would need to be written.

Thanks,
Rich

**Comment by sekhardutta** [comment]
Hi Rich

Please let me know if you find the param which we can use in java code to Exclude generated and external data by appliance in Review Changes.   I have checked SOMA schema for get-diff and I didn't find any. For now I am planning to write an XSLT to ignore this data from the response of SOMA.

Regards
Sekhar Dutta
